"""empty message

Revision ID: acf5346c6e36
Revises: 
Create Date: 2026-04-24 19:25:05.640837

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'acf5346c6e36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('name_uz', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attributes_deleted_at'), 'attributes', ['deleted_at'], unique=False)
    op.create_table('brands',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_oem', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_brands_deleted_at'), 'brands', ['deleted_at'], unique=False)
    op.create_table('categories',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name_uz', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key'),
    sa.UniqueConstraint('parent_id', 'slug'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_categories_deleted_at'), 'categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('manufacturers',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_deleted_at'), 'manufacturers', ['deleted_at'], unique=False)
    op.create_table('parts',
    sa.Column('name_uz', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_deleted_at'), 'parts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_parts_slug'), 'parts', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('car_models',
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generation', sa.String(), nullable=False),
    sa.Column('start_year', sa.Date(), nullable=False),
    sa.Column('end_year', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_models_deleted_at'), 'car_models', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_car_models_manufacturer_id'), 'car_models', ['manufacturer_id'], unique=False)
    op.create_table('category_attributes',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('is_filterable', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'attribute_id')
    )
    op.create_index(op.f('ix_category_attributes_attribute_id'), 'category_attributes', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_category_attributes_category_id'), 'category_attributes', ['category_id'], unique=False)
    op.create_index(op.f('ix_category_attributes_deleted_at'), 'category_attributes', ['deleted_at'], unique=False)
    op.create_table('part_category_links',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'category_id')
    )
    op.create_index(op.f('ix_part_category_links_category_id'), 'part_category_links', ['category_id'], unique=False)
    op.create_index(op.f('ix_part_category_links_deleted_at'), 'part_category_links', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_part_category_links_part_id'), 'part_category_links', ['part_id'], unique=False)
    op.create_table('part_numbers',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('is_oem', sa.Boolean(), nullable=False),
    sa.Column('replaced_by_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['replaced_by_id'], ['part_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_id', 'number')
    )
    op.create_index(op.f('ix_part_numbers_brand_id'), 'part_numbers', ['brand_id'], unique=False)
    op.create_index(op.f('ix_part_numbers_deleted_at'), 'part_numbers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_part_numbers_number'), 'part_numbers', ['number'], unique=False)
    op.create_index(op.f('ix_part_numbers_part_id'), 'part_numbers', ['part_id'], unique=False)
    op.create_index(op.f('ix_part_numbers_replaced_by_id'), 'part_numbers', ['replaced_by_id'], unique=False)
    op.create_table('car_modifications',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('engine_code', sa.String(), nullable=False),
    sa.Column('engine_volume', sa.String(), nullable=False),
    sa.Column('fuel_type', sa.String(), nullable=False),
    sa.Column('power_hp', sa.String(), nullable=False),
    sa.Column('year_from', sa.Date(), nullable=False),
    sa.Column('year_to', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['car_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_modifications_deleted_at'), 'car_modifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_car_modifications_model_id'), 'car_modifications', ['model_id'], unique=False)
    op.create_table('cross_references',
    sa.Column('part_number_id', sa.Integer(), nullable=False),
    sa.Column('cross_part_number_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cross_part_number_id'], ['part_numbers.id'], ),
    sa.ForeignKeyConstraint(['part_number_id'], ['part_numbers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number_id', 'cross_part_number_id')
    )
    op.create_index(op.f('ix_cross_references_cross_part_number_id'), 'cross_references', ['cross_part_number_id'], unique=False)
    op.create_index(op.f('ix_cross_references_deleted_at'), 'cross_references', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cross_references_part_number_id'), 'cross_references', ['part_number_id'], unique=False)
    op.create_table('products',
    sa.Column('part_number_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('selling_price', sa.DECIMAL(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['part_number_id'], ['part_numbers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_part_number_id'), 'products', ['part_number_id'], unique=False)
    op.create_table('part_fitments',
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('car_modification_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_modification_id'], ['car_modifications.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_id', 'car_modification_id')
    )
    op.create_index(op.f('ix_part_fitments_car_modification_id'), 'part_fitments', ['car_modification_id'], unique=False)
    op.create_index(op.f('ix_part_fitments_deleted_at'), 'part_fitments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_part_fitments_part_id'), 'part_fitments', ['part_id'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_number', sa.DECIMAL(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'attribute_id')
    )
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_deleted_at'), 'product_attribute_values', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_product_id'), 'product_attribute_values', ['product_id'], unique=False)
    op.create_table('stocks',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.DECIMAL(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('quantity >= 0'),
    sa.CheckConstraint('reserved_quantity >= 0'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_deleted_at'), 'stocks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stocks_product_id'), 'stocks', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_product_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_deleted_at'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_product_attribute_values_product_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_deleted_at'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_part_fitments_part_id'), table_name='part_fitments')
    op.drop_index(op.f('ix_part_fitments_deleted_at'), table_name='part_fitments')
    op.drop_index(op.f('ix_part_fitments_car_modification_id'), table_name='part_fitments')
    op.drop_table('part_fitments')
    op.drop_index(op.f('ix_products_part_number_id'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_cross_references_part_number_id'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_deleted_at'), table_name='cross_references')
    op.drop_index(op.f('ix_cross_references_cross_part_number_id'), table_name='cross_references')
    op.drop_table('cross_references')
    op.drop_index(op.f('ix_car_modifications_model_id'), table_name='car_modifications')
    op.drop_index(op.f('ix_car_modifications_deleted_at'), table_name='car_modifications')
    op.drop_table('car_modifications')
    op.drop_index(op.f('ix_part_numbers_replaced_by_id'), table_name='part_numbers')
    op.drop_index(op.f('ix_part_numbers_part_id'), table_name='part_numbers')
    op.drop_index(op.f('ix_part_numbers_number'), table_name='part_numbers')
    op.drop_index(op.f('ix_part_numbers_deleted_at'), table_name='part_numbers')
    op.drop_index(op.f('ix_part_numbers_brand_id'), table_name='part_numbers')
    op.drop_table('part_numbers')
    op.drop_index(op.f('ix_part_category_links_part_id'), table_name='part_category_links')
    op.drop_index(op.f('ix_part_category_links_deleted_at'), table_name='part_category_links')
    op.drop_index(op.f('ix_part_category_links_category_id'), table_name='part_category_links')
    op.drop_table('part_category_links')
    op.drop_index(op.f('ix_category_attributes_deleted_at'), table_name='category_attributes')
    op.drop_index(op.f('ix_category_attributes_category_id'), table_name='category_attributes')
    op.drop_index(op.f('ix_category_attributes_attribute_id'), table_name='category_attributes')
    op.drop_table('category_attributes')
    op.drop_index(op.f('ix_car_models_manufacturer_id'), table_name='car_models')
    op.drop_index(op.f('ix_car_models_deleted_at'), table_name='car_models')
    op.drop_table('car_models')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_parts_slug'), table_name='parts')
    op.drop_index(op.f('ix_parts_deleted_at'), table_name='parts')
    op.drop_table('parts')
    op.drop_index(op.f('ix_manufacturers_deleted_at'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_deleted_at'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_deleted_at'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_attributes_deleted_at'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
