"""empty message

Revision ID: efc04191d7f8
Revises: 51f4f903ba29
Create Date: 2026-04-29 15:19:36.542392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc04191d7f8'
down_revision: Union[str, Sequence[str], None] = '51f4f903ba29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_uuid', sa.UUID(), nullable=False))
    op.add_column('users', sa.Column('_password', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_user_uuid'), 'users', ['user_uuid'], unique=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_user_uuid'), table_name='users')
    op.drop_column('users', '_password')
    op.drop_column('users', 'user_uuid')
    # ### end Alembic commands ###
